// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/**
 * @title Service Chain Verifier for Industry 5.0 Energy Trading
 * @notice Implements the "Logic Verification Action" described in Section III-B.
 * @dev Deployed on Hyperledger Besu (Chain A).
 */

// Interface for the ZK-SNARK Verifier (Generated by ZoKrates)
interface IVerifier {
    function verifyTx(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[6] memory input // Public inputs matching the circuit
    ) external view returns (bool r);
}

contract ServiceChainVerifier {
    
    IVerifier public zkpVerifier;
    address public admin;

    // --- Events ---
    // This event acts as the "Signal" for the Cross-Chain Bridge
    // Corresponds to "emit ChargingStarted" in the paper's algorithm
    event ChargingStarted(
        address indexed me_agent,  // The Mobile Embodied Agent (MEA)
        uint256 energy_req,        // Requested Energy Amount
        uint256 timestamp,         // Logic Timestamp
        bytes32 session_hash       // Unique Session ID to prevent replays
    );

    constructor(address _verifierAddress) {
        zkpVerifier = IVerifier(_verifierAddress);
        admin = msg.sender;
    }

    /**
     * @notice Main entry point for Agents to submit proofs
     * @param a - Groth16 proof parameter A
     * @param b - Groth16 proof parameter B
     * @param c - Groth16 proof parameter C
     * @param input - Public inputs: [xm, ym, r_sq, e_max, e_req, identity_commitment]
     * @param session_id - Unique session nonce
     */
    function submitTradingRequest(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[6] memory input, 
        bytes32 session_id
    ) public {
        
        // 1. ZK-Proof Verification (Computational Integrity)
        // Checks: (x-x')^2 <= R^2 AND Battery Safety
        bool isProofValid = zkpVerifier.verifyTx(a, b, c, input);
        require(isProofValid, "Access Denied: Invalid Geo-ZKP Proof or Safety Violation");

        // 2. Extract Business Logic Data
        // input[4] corresponds to 'e_req' based on our circuit definition
        uint256 energyAmount = input[4]; 

        // 3. Emit Cross-Chain Signal
        // The off-chain Bridge will listen to this event and trigger Payment on Chain B
        emit ChargingStarted(msg.sender, energyAmount, block.timestamp, session_id);
    }
}
